
BUILD = ./build
CSRC = $(shell find $(abspath ./csrc) -name "*.c")
INCLUDE = ./

run: 
	gcc -o $(BUILD)/cachesim $(CSRC) -I
	$(BUILD)/cachesim /home/dengzibin/ysyx-workbench/nemu/build/pctrace_train.bin